// Copyright 2026 Hyperscale. All rights reserved.
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.

// Command derive-corpus regenerates the testdata files that are derived
// from other testdata files.
//
// Sources of truth:
//   - testdata/siret/fr-valide.txt  (14-digit SIRETs)
//   - testdata/registers/<cc>-valide.txt  (national register segments)
//   - testdata/vat/<cc>-valide.txt  (VAT numbers, not derived — hand-collected)
//
// Derived outputs:
//   - testdata/siren/fr-valide.txt  = unique(siret[:9])
//   - testdata/registers/fr-valide.txt = same content as testdata/siren/fr-valide.txt
//   - testdata/euid/<cc>-valide.txt = "<CC><REGISTER>." + registers/<cc>-valide.txt
//
// Run from the module root:
//
//	go run ./hack/derive-corpus
//
// The tool is idempotent: re-running with unchanged sources produces no
// diff. CI can run it to catch drift.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// registerCodes maps each EU-27 country to the REGISTER segment used in
// its EUID (aligned with the existing test fixtures in
// providers/euid/euid_test.go).
var registerCodes = map[string]string{
	"AT": "FN",
	"BE": "BCE",
	"BG": "EIK",
	"CY": "HE",
	"CZ": "OR",
	"DE": "HRB",
	"DK": "CVR",
	"EE": "RIK",
	"EL": "GEMI",
	"ES": "RMC",
	"FI": "PRH",
	"FR": "RCS",
	"HR": "MBS",
	"HU": "CG",
	"IE": "CRO",
	"IT": "RI",
	"LT": "JAR",
	"LU": "RCSL",
	"LV": "URE",
	"MT": "MBR",
	"NL": "KVK",
	"PL": "KRS",
	"PT": "RN",
	"RO": "ORCT",
	"SE": "BR",
	"SI": "SRG",
	"SK": "OR",
}

const derivedHeader = "# GENERATED by hack/derive-corpus — do not edit by hand.\n# Re-generate with: go run ./hack/derive-corpus\n"

func main() {
	root, err := repoRoot()
	if err != nil {
		fatal(err)
	}

	if err := deriveSIRENFromSIRET(root); err != nil {
		fatal(err)
	}

	if err := deriveAllEUIDs(root); err != nil {
		fatal(err)
	}

	logInfo("done")
}

// logInfo writes a "derive-corpus: <msg>" line to stderr via the log
// package (fmt.Print* is banned by our lint config).
func logInfo(msg string) {
	log.SetFlags(0)
	log.Println("derive-corpus:", msg)
}

// deriveSIRENFromSIRET reads testdata/siret/fr-valide.txt and writes:
//   - testdata/siren/fr-valide.txt = unique(siret[:9]), sorted
//   - testdata/registers/fr-valide.txt = same (the FR EUID registration
//     segment IS the SIREN)
func deriveSIRENFromSIRET(root string) error {
	sirets, err := readPayload(filepath.Join(root, "testdata", "siret", "fr-valide.txt"))
	if err != nil {
		if os.IsNotExist(err) {
			logInfo("testdata/siret/fr-valide.txt missing, skipping SIREN derivation")

			return nil
		}

		return err
	}

	seen := make(map[string]struct{}, len(sirets))
	sirens := make([]string, 0, len(sirets))

	for _, s := range sirets {
		if len(s) < 9 {
			return fmt.Errorf("bad SIRET %q (need 14 digits, got %d)", s, len(s))
		}

		siren := s[:9]
		if _, ok := seen[siren]; ok {
			continue
		}

		seen[siren] = struct{}{}
		sirens = append(sirens, siren)
	}

	sort.Strings(sirens)

	if err := writeDerived(filepath.Join(root, "testdata", "siren", "fr-valide.txt"), sirens); err != nil {
		return err
	}

	return writeDerived(filepath.Join(root, "testdata", "registers", "fr-valide.txt"), sirens)
}

// deriveAllEUIDs walks testdata/registers/*.txt and produces the
// matching EUID file by prepending "<CC><REGISTER>." to each line.
func deriveAllEUIDs(root string) error {
	regDir := filepath.Join(root, "testdata", "registers")

	entries, err := os.ReadDir(regDir)
	if err != nil {
		if os.IsNotExist(err) {
			logInfo("testdata/registers/ missing, skipping EUID derivation")

			return nil
		}

		return fmt.Errorf("read dir %s: %w", regDir, err)
	}

	for _, e := range entries {
		if e.IsDir() {
			continue
		}

		name := e.Name()
		if !strings.HasSuffix(name, "-valide.txt") {
			continue
		}

		cc := strings.ToUpper(strings.TrimSuffix(name, "-valide.txt"))

		reg, ok := registerCodes[cc]
		if !ok {
			return fmt.Errorf("no register code mapped for country %q (file %s)", cc, name)
		}

		regs, err := readPayload(filepath.Join(regDir, name))
		if err != nil {
			return err
		}

		euids := make([]string, len(regs))

		prefix := cc + reg + "."
		for i, r := range regs {
			euids[i] = prefix + r
		}

		out := filepath.Join(root, "testdata", "euid", strings.ToLower(cc)+"-valide.txt")
		if err := writeDerived(out, euids); err != nil {
			return err
		}
	}

	return nil
}

// readPayload returns non-empty, non-comment lines from a testdata file.
func readPayload(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	var out []string

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		out = append(out, line)
	}

	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("scan %s: %w", path, err)
	}

	return out, nil
}

// writeDerived writes lines to path with a generated-header banner. It
// creates parent directories if needed.
func writeDerived(path string, lines []string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}

	var b strings.Builder

	b.WriteString(derivedHeader)

	for _, l := range lines {
		b.WriteString(l)
		b.WriteByte('\n')
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	return nil
}

// repoRoot returns the workspace root — the directory that contains
// go.work (preferred) or, failing that, the outermost go.mod. The
// derive-corpus tool depends on the layout of testdata/ under the
// repository root, so this must skip the tool's own sub-module.
func repoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}

	// Walk up looking for go.work — that's the workspace root, which
	// is the only unambiguous marker when nested modules exist.
	dir := cwd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}

		dir = parent
	}

	// Fallback for non-workspace invocations: walk up until we find a
	// go.mod that also has a testdata/ directory alongside it. That
	// combination identifies the repo root even without go.work.
	dir = cwd
	for {
		_, modErr := os.Stat(filepath.Join(dir, "go.mod"))
		_, testdataErr := os.Stat(filepath.Join(dir, "testdata"))

		if modErr == nil && testdataErr == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("repo root (go.work or go.mod + testdata/) not found starting from %s", cwd)
		}

		dir = parent
	}
}

func fatal(err error) {
	logInfo(err.Error())
	os.Exit(1)
}
